version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db