/*
 * CREATE SCRIPT
 */
DROP DATABASE IF EXISTS Crm;
CREATE DATABASE Crm;
USE Crm;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(255),
	is_enabled BOOLEAN DEFAULT TRUE,
	tg_id BIGINT UNIQUE NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE resources (
	id INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
	is_enabled BOOLEAN DEFAULT TRUE,
	name VARCHAR(20)	
);

CREATE TABLE roles (
	id INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20)
);


CREATE TABLE accounts (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255),
	surname VARCHAR(255),
	role_id INT UNSIGNED NOT NULL,
	phone VARCHAR(255),
	email VARCHAR(255),
	sex VARCHAR(255),
	verified BOOLEAN DEFAULT FALSE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (id) REFERENCES users(id)
);


CREATE TABLE res_roles (
	id SERIAL PRIMARY KEY,
	role_id INT UNSIGNED NOT NULL,
	resource_id INT UNSIGNED NOT NULL,
	
	FOREIGN KEY (role_id) REFERENCES roles(id),
	FOREIGN KEY (resource_id) REFERENCES resources(id)
);



























